name: Swift Build Makefile CI for macOS

on:
  push:
    branches: [ "change-value-limit" ]
  pull_request:
    branches: [ "change-value-limit" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install build
      run: make build
      
    - name: Run Test
      run: make test
